# Generated by Django 4.2.30 on 2026-10-02 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreservationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('VEG', 'Sayur & Buah'), ('MEAT', 'Daging & Protein'), ('DAIRY', 'Produk Olahan Susu'), ('GRAIN', 'Biji-bijian & Makanan Kering'), ('OTHER', 'Lainnya')], default='OTHER', max_length=10)),
                ('preservation_method', models.CharField(help_text='Contoh: Freezing, Pickling, Dehydration', max_length=100)),
                ('content', models.TextField(help_text='Langkah-langkah pengawetan bahan makanan.')),
                ('smell_indicator', models.TextField(help_text='Ciri-ciri aroma bahan yang masih layak vs sudah rusak.')),
                ('texture_indicator', models.TextField(help_text='Perubahan tekstur yang perlu diwaspadai.')),
                ('visual_indicator', models.TextField(help_text='Perubahan warna atau tampilan fisik (misal: jamur).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_guides', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_guides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
