# Generated by Django 5.2.17 on 2026-10-03 01:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nama bahan")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("VEG", "Sayur & Buah"),
                            ("MEAT", "Daging & Protein"),
                            ("DAIRY", "Produk Olahan Susu"),
                            ("GRAIN", "Biji-bijian & Makanan Kering"),
                            ("OTHER", "Lainnya"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="kategori",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                        verbose_name="jumlah",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "buah"),
                            ("butir", "butir"),
                            ("pack", "bungkus"),
                            ("ikat", "ikat"),
                            ("g", "gram"),
                            ("kg", "kg"),
                            ("ml", "ml"),
                            ("l", "liter"),
                        ],
                        default="pcs",
                        max_length=10,
                        verbose_name="satuan",
                    ),
                ),
                (
                    "storage",
                    models.CharField(
                        choices=[
                            ("FRIDGE", "Kulkas"),
                            ("FREEZER", "Freezer"),
                            ("PANTRY", "Rak dapur"),
                        ],
                        default="FRIDGE",
                        max_length=10,
                        verbose_name="tempat simpan",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="tanggal beli",
                    ),
                ),
                ("expiry_date", models.DateField(verbose_name="perkiraan kedaluwarsa")),
                ("expiry_is_estimate", models.BooleanField(default=False)),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="catatan"
                    ),
                ),
                ("resurrected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pantry_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bahan inventaris",
                "verbose_name_plural": "bahan inventaris",
                "ordering": ["expiry_date", "name"],
                "indexes": [
                    models.Index(
                        fields=["user", "expiry_date"],
                        name="death_clock_user_id_db173e_idx",
                    )
                ],
            },
        ),
    ]
